version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/maven-multi-module"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - Mauro2888
    groups:
      spring-dependencies:
        patterns:
          - "org.springframework*"
      test-dependencies:
        patterns:
          - "org.junit*"
          - "org.mockito*"
          - "org.assertj*"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - Mauro2888
    commit-message:
      prefix: "ci"
      include: "scope"