# Workflow Monitoring Dependabot updates
name: CI-dependabot-events

on:
  pull_request_target:
    branches:
      - 'dependabot/**'
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  monitor:
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Log Dependabot Event
        run: |
          echo "Dependabot event detected: ${{ github.event.action }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }}"