name: CI

on:
  push:
    branches-ignore:
      - main
      - test
      - dependabot/**
    tags-ignore:
      - '*'

jobs:
  ci:
    env:
      VERSION: 4.0.0
      GITHUB_USERNAME: Mauro2888
      GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
      JAVA_PROJECT_ROOT_MODULE : maven-multi-module
      MVN_SETTINGS: ./.github/workflows/settings.xml
      MVN_REPO: ~/.m2/repository


    runs-on: ubuntu-22.04

    steps:
      - name: Log Workflow Version
        run: |
          echo "Workflow Version: ${{ env.VERSION }}"

      - name: Checkout Module Repository
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Load Common Environment Variables
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: ./.github/workflows/common-env
          load-mode: strict

      - name: Log Common Environment Variables
        run: |
          echo "Java Distribution: ${{ env.JAVA_DISTRIBUTION }}"
          echo "Java Version: ${{ env.JAVA_VERSION }}"

      - name: Setup JDK ${{ env.JAVA_DISTRIBUTION }} ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.6.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
          check-latest: false

      - name: Maven Jar Module Build
        run: mvn -B --settings $MVN_SETTINGS -f $JAVA_PROJECT_ROOT_MODULE/pom.xml -T1C verify