name: Export Database Schema (Maven)
on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: stock_trading
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Wait for database
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then break; fi
            sleep 2
          done

      - name: Run Liquibase (exactly like local)
        run: |
          mvn liquibase:update \
            -Dliquibase.changeLogFile="src/main/resources/db/db-changelog-master.yml" \
            -Dliquibase.url="jdbc:postgresql://localhost:5432/stock_trading" \
            -Dliquibase.username="postgres" \
            -Dliquibase.password="postgres" \
            -Dliquibase.verbose=true

      - name: Export and commit
        run: |
          PGPASSWORD=postgres pg_dump -h localhost -U postgres stock_trading > database-export.sql
          
          mkdir -p exports
          mv database-export.sql exports/
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add exports/
          git commit -m "Database export $(date)" || true
          git push || true